### PR TITLE
show page view for plants

### PR DESCRIPTION
**Pull request by LesBurdock**
show page for plants is done.. 
used placeholder images for the moment :)

### CODE REVIEW

**Comment by LesBurdock** [comment]
ps the page is also responsive for iphone and ipad using media queries ;)

**Comment by LesBurdock** [comment]
after pulling the new code from master remeber to re-seed the database (as i added extra text to the description etc)

**Comment by LesBurdock** [comment]
note to self I must make the logo smaller fro the responsive design to work well...

**Comment by mama-byte** [comment]
Merged. When ready, y'all should pull the recent master to continue to branch off.

**Pull request merged**
